-- MySQL Script generated by MySQL Workbench
-- Thu May  4 10:20:44 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`customer` (
  `Customer ID` INT NOT NULL,
  `Last Name` VARCHAR(500) NULL,
  `First Name` VARCHAR(500) NULL,
  `Email` VARCHAR(500) NULL,
  `Phone` VARCHAR(45) NULL,
  PRIMARY KEY (`Customer ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order` (
  `Order ID` INT NOT NULL,
  `Order Date` DATETIME NULL,
  `Order Priority` VARCHAR(45) NULL,
  `customer_Customer ID` INT NOT NULL,
  `Total cost` DECIMAL(10) NULL,
  PRIMARY KEY (`Order ID`),
  INDEX `fk_order_customer1_idx` (`customer_Customer ID` ASC) VISIBLE,
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_Customer ID`)
    REFERENCES `mydb`.`customer` (`Customer ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`category` (
  `Category ID` INT NOT NULL,
  `Category Name` VARCHAR(500) NULL,
  `category_Category ID` INT NOT NULL,
  PRIMARY KEY (`Category ID`),
  INDEX `fk_category_category1_idx` (`category_Category ID` ASC) VISIBLE,
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`category_Category ID`)
    REFERENCES `mydb`.`category` (`Category ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`product` (
  `Product ID` INT NOT NULL,
  `Product Name` VARCHAR(500) NULL,
  `Product Price` DECIMAL(10) NULL,
  `category_Category ID` INT NOT NULL,
  PRIMARY KEY (`Product ID`),
  INDEX `fk_product_category1_idx` (`category_Category ID` ASC) VISIBLE,
  CONSTRAINT `fk_product_category1`
    FOREIGN KEY (`category_Category ID`)
    REFERENCES `mydb`.`category` (`Category ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`order item` (
  `Order Item ID` INT NOT NULL,
  `qty` INT NULL,
  `product_Product ID` INT NOT NULL,
  `order_Order ID` INT NOT NULL,
  PRIMARY KEY (`Order Item ID`),
  INDEX `fk_order item_product_idx` (`product_Product ID` ASC) VISIBLE,
  INDEX `fk_order item_order1_idx` (`order_Order ID` ASC) VISIBLE,
  CONSTRAINT `fk_order item_product`
    FOREIGN KEY (`product_Product ID`)
    REFERENCES `mydb`.`product` (`Product ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order item_order1`
    FOREIGN KEY (`order_Order ID`)
    REFERENCES `mydb`.`order` (`Order ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`address` (
  `Address ID` INT NOT NULL,
  `Postcode` VARCHAR(45) NULL,
  `City` VARCHAR(500) NULL,
  `State` VARCHAR(500) NULL,
  `Street line one` VARCHAR(500) NULL,
  `Street line two` VARCHAR(500) NULL,
  `default` BINARY(1) NULL,
  `customer_Customer ID` INT NOT NULL,
  `Country` VARCHAR(500) NULL,
  PRIMARY KEY (`Address ID`),
  INDEX `fk_address_customer1_idx` (`customer_Customer ID` ASC) VISIBLE,
  CONSTRAINT `fk_address_customer1`
    FOREIGN KEY (`customer_Customer ID`)
    REFERENCES `mydb`.`customer` (`Customer ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`shipping`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`shipping` (
  `Shipping ID` INT NOT NULL,
  `address_Address ID` INT NOT NULL,
  `order_Order ID` INT NOT NULL,
  `Ship Date` DATETIME NULL,
  `Ship Mode` VARCHAR(500) NULL,
  `Shipping Cost` DECIMAL(10) NULL,
  PRIMARY KEY (`Shipping ID`),
  INDEX `fk_shipping_address1_idx` (`address_Address ID` ASC) VISIBLE,
  INDEX `fk_shipping_order1_idx` (`order_Order ID` ASC) VISIBLE,
  CONSTRAINT `fk_shipping_address1`
    FOREIGN KEY (`address_Address ID`)
    REFERENCES `mydb`.`address` (`Address ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shipping_order1`
    FOREIGN KEY (`order_Order ID`)
    REFERENCES `mydb`.`order` (`Order ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`discount`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`discount` (
  `Discount ID` INT NOT NULL,
  `Discount Name` VARCHAR(45) NULL,
  `Discount code` VARCHAR(45) NULL,
  PRIMARY KEY (`Discount ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`discount item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`discount item` (
  `Discount Item ID` INT NOT NULL,
  `Discount` DECIMAL(10) NULL,
  `discount_Discount ID` INT NOT NULL,
  `order_Order ID` INT NOT NULL,
  PRIMARY KEY (`Discount Item ID`),
  INDEX `fk_discount item_discount1_idx` (`discount_Discount ID` ASC) VISIBLE,
  INDEX `fk_discount item_order1_idx` (`order_Order ID` ASC) VISIBLE,
  CONSTRAINT `fk_discount item_discount1`
    FOREIGN KEY (`discount_Discount ID`)
    REFERENCES `mydb`.`discount` (`Discount ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_discount item_order1`
    FOREIGN KEY (`order_Order ID`)
    REFERENCES `mydb`.`order` (`Order ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;